/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sindnutri.telas;

import javax.swing.JOptionPane;
import sindnutri.models.ListaPaciente;
import sindnutri.models.Paciente;
import sindnutri.telas.TelaInicial;

/**
 *
 * @author breno
 */
public class Cadastro extends javax.swing.JFrame {
    private TelaInicial telaInicial;
    /**
     * Creates new form Cadastro
     */
    public Cadastro(TelaInicial telaInicial) {
        this.telaInicial = telaInicial;
        initComponents();
        
    }
    public Cadastro(){
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LbInicio = new javax.swing.JLabel();
        LbNome = new javax.swing.JLabel();
        LbTelefone = new javax.swing.JLabel();
        LbCPF = new javax.swing.JLabel();
        LbData = new javax.swing.JLabel();
        BtCadastrar = new javax.swing.JButton();
        CbPaciente = new javax.swing.JCheckBox();
        TxNome = new javax.swing.JTextField();
        TxTelefone = new javax.swing.JTextField();
        TxCpf = new javax.swing.JTextField();
        TxData = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        LbInicio.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LbInicio.setForeground(new java.awt.Color(0, 0, 0));
        LbInicio.setText("Cadastrar Consulta");

        LbNome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LbNome.setForeground(new java.awt.Color(0, 0, 0));
        LbNome.setText("Nome do(a) Paciente:");

        LbTelefone.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LbTelefone.setForeground(new java.awt.Color(0, 0, 0));
        LbTelefone.setText("Telefone:");

        LbCPF.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LbCPF.setForeground(new java.awt.Color(0, 0, 0));
        LbCPF.setText("CPF:");

        LbData.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LbData.setForeground(new java.awt.Color(0, 0, 0));
        LbData.setText("Data da Consulta:");

        BtCadastrar.setForeground(new java.awt.Color(0, 0, 0));
        BtCadastrar.setText("Cadastrar");
        BtCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtCadastrarActionPerformed(evt);
            }
        });

        CbPaciente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CbPaciente.setForeground(new java.awt.Color(0, 0, 0));
        CbPaciente.setText("Já é paciente");
        CbPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbPacienteActionPerformed(evt);
            }
        });

        TxNome.setForeground(new java.awt.Color(0, 0, 0));
        TxNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxNomeActionPerformed(evt);
            }
        });

        TxTelefone.setForeground(new java.awt.Color(0, 0, 0));
        TxTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxTelefoneActionPerformed(evt);
            }
        });

        TxCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxCpfActionPerformed(evt);
            }
        });

        TxData.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LbInicio)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LbNome)
                            .addComponent(LbTelefone)
                            .addComponent(LbCPF)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(CbPaciente)
                                .addComponent(LbData)))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TxCpf, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                            .addComponent(TxTelefone)
                            .addComponent(TxNome)
                            .addComponent(TxData)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(BtCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LbInicio)
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbNome)
                    .addComponent(TxNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbTelefone)
                    .addComponent(TxTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbCPF)
                    .addComponent(TxCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TxData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(LbData)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CbPaciente)))
                .addGap(12, 12, 12)
                .addComponent(BtCadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 26, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TxCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxCpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxCpfActionPerformed

    private void TxTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxTelefoneActionPerformed

    private void TxNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxNomeActionPerformed

    private void CbPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CbPacienteActionPerformed

    private void BtCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtCadastrarActionPerformed
        // TODO add your handling code here:
        Paciente paciente = new Paciente();
        
        paciente.setNome(TxNome.getText());
        paciente.setTelefone(TxTelefone.getText());
        paciente.setCpf(TxCpf.getText());
        paciente.setData(TxData.getText());
        paciente.setIsPaciente(CbPaciente.isSelected());       

        if(emptyFields() == false){
            if(!paciente.validarTelefone(paciente.getTelefone())){
                JOptionPane.showMessageDialog(rootPane, "Formato do TELEFONE inválido!\nEx:DDD123456789");
            }else if(!paciente.validarCPF(paciente.getCpf())){
                JOptionPane.showMessageDialog(rootPane, "Formato do CPF inválido!\nEx:123.456.789-00");
            }else if(!paciente.validarData(paciente.getData())){
                JOptionPane.showMessageDialog(rootPane, "Formato de DATA inválido!\nEx:12/34/5678");
                return;
            }else{
                ListaPaciente.adicionar(paciente);
                telaInicial.atualizarTable();
                JOptionPane.showMessageDialog(rootPane, paciente.getNome() + " Cadastro concluído");
            }
             if (telaInicial != null) {
                telaInicial.atualizarTable();
    }
             dispose();
        }

    }//GEN-LAST:event_BtCadastrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtCadastrar;
    private javax.swing.JCheckBox CbPaciente;
    private javax.swing.JLabel LbCPF;
    private javax.swing.JLabel LbData;
    private javax.swing.JLabel LbInicio;
    private javax.swing.JLabel LbNome;
    private javax.swing.JLabel LbTelefone;
    private javax.swing.JTextField TxCpf;
    private javax.swing.JTextField TxData;
    private javax.swing.JTextField TxNome;
    private javax.swing.JTextField TxTelefone;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
    
    public boolean emptyFields(){
       boolean empty = true;
        if(TxNome.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Preencha o campo NOME!");
        }else if(TxTelefone.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Preencha o campo TELEFONE!");
        }else if(TxCpf.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Preencha o campo CPF!");
        }else if(TxData.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Preencha o campo DATA!");
        }else{
            empty = false;
        }
        return empty;
    }
}
