/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sindnutri.telas;

import javax.swing.JOptionPane;
import sindnutri.models.Paciente;

/**
 *
 * @author breno
 */
public class ConsuDetalhes extends javax.swing.JFrame {
    private Paciente paciente;
    private TelaInicial telaInicial;
    /**
     * Creates new form ConsuDetalhes
     */
    public ConsuDetalhes(TelaInicial telaInicial, Paciente paciente) {
        this.telaInicial = telaInicial;
        this.paciente = paciente;
        initComponents();
        exibir();
    }
    public ConsuDetalhes(){
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LbInicio = new javax.swing.JLabel();
        CbConsulta = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        TxaReceita = new javax.swing.JTextArea();
        LbReceita = new javax.swing.JLabel();
        BtFinalizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        LbInicio.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LbInicio.setForeground(new java.awt.Color(0, 0, 0));
        LbInicio.setText("Detalhes da Consulta");

        CbConsulta.setForeground(new java.awt.Color(0, 0, 0));
        CbConsulta.setText("Consulta Realizada");
        CbConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbConsultaActionPerformed(evt);
            }
        });

        TxaReceita.setColumns(20);
        TxaReceita.setForeground(new java.awt.Color(0, 0, 0));
        TxaReceita.setRows(5);
        TxaReceita.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jScrollPane1.setViewportView(TxaReceita);

        LbReceita.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        LbReceita.setForeground(new java.awt.Color(0, 0, 0));
        LbReceita.setText("Receita e observações:");

        BtFinalizar.setForeground(new java.awt.Color(0, 0, 0));
        BtFinalizar.setText("Finalizar");
        BtFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtFinalizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LbInicio)
                            .addComponent(CbConsulta)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LbReceita)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtFinalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LbInicio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CbConsulta)
                .addGap(18, 18, 18)
                .addComponent(LbReceita)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtFinalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtFinalizarActionPerformed
        // TODO add your handling code here: 
        if (paciente != null) {
            String receita = TxaReceita.getText();
        if (!receita.isEmpty() && paciente.getIsStatus()) {
            paciente.setReceita(receita);
            telaInicial.atualizarTable();
            JOptionPane.showMessageDialog(this, "Consulta finalizada com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
            dispose();
         } else {
            JOptionPane.showMessageDialog(this, "Por favor, insira a receita ou observação e sinaliza caixa de consulta realizada antes de finalizar.", "Erro", JOptionPane.ERROR_MESSAGE);
        }

    }
           
    }//GEN-LAST:event_BtFinalizarActionPerformed

    private void CbConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbConsultaActionPerformed
        // TODO add your handling code here:
      if (paciente != null) {
        paciente.setIsStatus(CbConsulta.isSelected());
    }
        
    }//GEN-LAST:event_CbConsultaActionPerformed

    /**
     * @param args the command line argumentsz
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsuDetalhes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsuDetalhes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsuDetalhes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsuDetalhes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsuDetalhes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtFinalizar;
    private javax.swing.JCheckBox CbConsulta;
    private javax.swing.JLabel LbInicio;
    private javax.swing.JLabel LbReceita;
    private javax.swing.JTextArea TxaReceita;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    
    private void exibir(){
    if (paciente != null && paciente.getIsStatus()) {
            CbConsulta.setSelected(true);
            CbConsulta.setEnabled(false); // Desabilita checkbox para consulta realizada
            BtFinalizar.setVisible(false); // Esconde o botão de finalizar se a consulta já foi realizada
            TxaReceita.setText(paciente.getReceita()); // Exibe a receita
        } else {
            CbConsulta.setEnabled(true); // Habilita checkbox se a consulta não foi realizada
            BtFinalizar.setVisible(true); // Exibe o botão de finalizar
        }
    }
    
}

