/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sindnutri.telas;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import sindnutri.models.ListaPaciente;
import sindnutri.models.Paciente;

/**
 *
 * @author breno
 */
public class TelaInicial extends javax.swing.JFrame {
    private DefaultTableModel tabela;
    /**
     * Creates new form TelaInicial
     */
    public TelaInicial() {
        initComponents();
        tabela = new DefaultTableModel(new Object[]{"Paciente", "CPF", "Telefone", "Data", "Já era paciente? ", "Consulta Realizada"}, 0);
        atualizarTable();
        Paciente paciente;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LbInicio = new javax.swing.JLabel();
        BtConsulta = new javax.swing.JButton();
        BtExcluir = new javax.swing.JButton();
        BtFinalizar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        JTabela = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        LbInicio.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LbInicio.setForeground(new java.awt.Color(0, 0, 0));
        LbInicio.setText("Boas vindas ao sistema de agendamento");

        BtConsulta.setText("Nova Consulta");
        BtConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtConsultaActionPerformed(evt);
            }
        });

        BtExcluir.setText("Excluir Consulta");
        BtExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtExcluirActionPerformed(evt);
            }
        });

        BtFinalizar.setText("Finalizar Consulta");
        BtFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtFinalizarActionPerformed(evt);
            }
        });

        JTabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Paciente", "CPF", "Telefone", "Data", "Já era paciente", "Consulta Realizada"
            }
        ));
        jScrollPane2.setViewportView(JTabela);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(LbInicio)
                        .addGap(0, 351, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(BtConsulta)
                        .addGap(160, 160, 160)
                        .addComponent(BtExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtFinalizar)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LbInicio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtFinalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtExcluirActionPerformed
        // TODO add your handling code here:
        int linhaSelecionada = JTabela.getSelectedRow();
         if (linhaSelecionada >= 0) {
            String nome = (String) JTabela.getValueAt(linhaSelecionada, 0);
            Paciente paciente = buscarNome(nome);
             if (paciente != null) {
                 ListaPaciente.remover(paciente); // Remove o paciente da lista
                 atualizarTable(); // Atualiza a tabela para refletir a remoção
                 JOptionPane.showMessageDialog(null, "Consulta excluída com sucesso!");
            } else {
                 JOptionPane.showMessageDialog(null, "Paciente não encontrado.");
}
}
    }//GEN-LAST:event_BtExcluirActionPerformed

    private void BtFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtFinalizarActionPerformed
        // TODO add your handling code here:
        int linhaSelecionada = JTabela.getSelectedRow();
        
        if(linhaSelecionada >= 0){
        String nome = (String) JTabela.getValueAt(linhaSelecionada, 0);
        Paciente paciente = buscarNome(nome);
        ConsuDetalhes telaFinalizar = new ConsuDetalhes(this, paciente);
        telaFinalizar.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(null, "Selecione o PACIENTE para finalizar a consulta!");
        }
    }//GEN-LAST:event_BtFinalizarActionPerformed

    private void BtConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtConsultaActionPerformed
        // TODO add your handling code here:        
        Cadastro telaCadastro = new Cadastro(this);
        telaCadastro.setVisible(true);
    }//GEN-LAST:event_BtConsultaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtConsulta;
    private javax.swing.JButton BtExcluir;
    private javax.swing.JButton BtFinalizar;
    private javax.swing.JTable JTabela;
    private javax.swing.JLabel LbInicio;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

    public void atualizarTable(){
       DefaultTableModel tabela = (DefaultTableModel) JTabela.getModel();
       tabela.setRowCount(0);
       for(Paciente paciente : ListaPaciente.listar()) {
        tabela.addRow(new Object[]{
            paciente.getNome(),
            paciente.getCpf(),
            paciente.getTelefone(),
            paciente.getData(),
            paciente.getIsPaciente() ? "Sim" : "Não",
            paciente.getIsStatus() ? "Sim" : "Não"
        });
    }
}
    public Paciente buscarNome(String nome){
        for(Paciente paciente : ListaPaciente.listar()){
            if(paciente.getNome().equalsIgnoreCase(nome)){
                return paciente;
            }
        } return null;
    }

    }
    
