/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package nutrisoft;

import javax.swing.JOptionPane;

/**
 *
 * @author breno
 */
public class GastoCalorico extends javax.swing.JFrame {

    /**
     * Creates new form GastoCalorico
     */
    public GastoCalorico() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        JpGastoCalorico = new javax.swing.JPanel();
        InputPanel = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        LbPeso = new javax.swing.JLabel();
        LbAltura = new javax.swing.JLabel();
        LbIdade = new javax.swing.JLabel();
        TxPeso = new javax.swing.JTextField();
        TxAltura = new javax.swing.JTextField();
        TxIdade = new javax.swing.JTextField();
        LbAtv = new javax.swing.JLabel();
        CbAtv = new javax.swing.JComboBox<>();
        BtCalcular = new javax.swing.JButton();
        LbTitle = new javax.swing.JLabel();
        OutPanel = new javax.swing.JPanel();
        LbGB = new javax.swing.JLabel();
        LbGT = new javax.swing.JLabel();
        LbRespGB = new javax.swing.JLabel();
        LbRespGT = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        JpGastoCalorico.setBackground(new java.awt.Color(204, 204, 204));
        JpGastoCalorico.setBorder(null);

        InputPanel.setBackground(new java.awt.Color(204, 204, 204));
        InputPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        InputPanel.setForeground(new java.awt.Color(0, 0, 0));

        jRadioButton1.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(0, 0, 0));
        jRadioButton1.setText("Mulher");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(0, 0, 0));
        jRadioButton2.setText("Homem");
        jRadioButton2.setFocusable(false);
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        LbPeso.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LbPeso.setForeground(new java.awt.Color(0, 0, 0));
        LbPeso.setText("Peso (kg):");

        LbAltura.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LbAltura.setForeground(new java.awt.Color(0, 0, 0));
        LbAltura.setText("Altura (cm):");

        LbIdade.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LbIdade.setForeground(new java.awt.Color(0, 0, 0));
        LbIdade.setText("Idade:");

        TxPeso.setBackground(new java.awt.Color(255, 255, 255));
        TxPeso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxPesoActionPerformed(evt);
            }
        });

        TxAltura.setBackground(new java.awt.Color(255, 255, 255));

        TxIdade.setBackground(new java.awt.Color(255, 255, 255));
        TxIdade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxIdadeActionPerformed(evt);
            }
        });

        LbAtv.setBackground(new java.awt.Color(0, 0, 0));
        LbAtv.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LbAtv.setForeground(new java.awt.Color(0, 0, 0));
        LbAtv.setText("Nível de Atividade:");

        CbAtv.setBackground(new java.awt.Color(255, 255, 255));
        CbAtv.setForeground(new java.awt.Color(204, 204, 204));
        CbAtv.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Sedentário", "Leve (Exerc. leve 1 a 3 dias/semana)", "Moderado (Exerc. moderado 3 a 5 dias/semana)", "Ativo (Exerc. pesado 5 a 6  dias/semana)", "Extremamente ativo (Exerc. pesado diário)" }));
        CbAtv.setToolTipText("");
        CbAtv.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        CbAtv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbAtvActionPerformed(evt);
            }
        });

        BtCalcular.setBackground(new java.awt.Color(255, 255, 255));
        BtCalcular.setForeground(new java.awt.Color(0, 0, 0));
        BtCalcular.setText("Calcular");
        BtCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtCalcularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout InputPanelLayout = new javax.swing.GroupLayout(InputPanel);
        InputPanel.setLayout(InputPanelLayout);
        InputPanelLayout.setHorizontalGroup(
            InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InputPanelLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jRadioButton1)
                        .addGap(57, 57, 57)
                        .addComponent(jRadioButton2)
                        .addContainerGap(92, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InputPanelLayout.createSequentialGroup()
                        .addGroup(InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(InputPanelLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(BtCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(InputPanelLayout.createSequentialGroup()
                                .addComponent(LbAtv)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(CbAtv, 0, 1, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, InputPanelLayout.createSequentialGroup()
                                .addGroup(InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LbPeso)
                                    .addComponent(LbAltura)
                                    .addComponent(LbIdade))
                                .addGap(76, 76, 76)
                                .addGroup(InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TxIdade)
                                    .addComponent(TxAltura)
                                    .addComponent(TxPeso))))
                        .addGap(27, 27, 27))))
        );
        InputPanelLayout.setVerticalGroup(
            InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InputPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LbPeso))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LbAltura))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LbIdade))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbAtv)
                    .addComponent(CbAtv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtCalcular, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        CbAtv.getAccessibleContext().setAccessibleName("");

        LbTitle.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        LbTitle.setForeground(new java.awt.Color(0, 0, 0));
        LbTitle.setText("Cálculo de Gasto Calórico");

        OutPanel.setBackground(new java.awt.Color(204, 204, 204));
        OutPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        OutPanel.setForeground(new java.awt.Color(0, 0, 0));

        LbGB.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LbGB.setForeground(new java.awt.Color(0, 0, 0));
        LbGB.setText("Gasto Basal:");

        LbGT.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LbGT.setForeground(new java.awt.Color(0, 0, 0));
        LbGT.setText("Gasto Total:");

        LbRespGB.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        LbRespGB.setForeground(new java.awt.Color(0, 0, 0));

        LbRespGT.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        LbRespGT.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout OutPanelLayout = new javax.swing.GroupLayout(OutPanel);
        OutPanel.setLayout(OutPanelLayout);
        OutPanelLayout.setHorizontalGroup(
            OutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OutPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(OutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LbGB)
                    .addComponent(LbGT))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(OutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LbRespGB, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                    .addComponent(LbRespGT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(25, 25, 25))
        );
        OutPanelLayout.setVerticalGroup(
            OutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OutPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(OutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LbRespGB, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LbGB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(OutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LbGT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LbRespGT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout JpGastoCaloricoLayout = new javax.swing.GroupLayout(JpGastoCalorico);
        JpGastoCalorico.setLayout(JpGastoCaloricoLayout);
        JpGastoCaloricoLayout.setHorizontalGroup(
            JpGastoCaloricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpGastoCaloricoLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(JpGastoCaloricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LbTitle)
                    .addComponent(OutPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(InputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        JpGastoCaloricoLayout.setVerticalGroup(
            JpGastoCaloricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpGastoCaloricoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LbTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(InputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(OutPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JpGastoCalorico, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JpGastoCalorico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void TxIdadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxIdadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxIdadeActionPerformed

    private void TxPesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxPesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxPesoActionPerformed

    private void CbAtvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbAtvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CbAtvActionPerformed

    private void BtCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtCalcularActionPerformed
        try{
            if(buttonGroup1.getSelection() == null || CbAtv.getSelectedIndex() == 0){
                JOptionPane.showMessageDialog(null, "Selecione uma das opções!");
                return;
            }else if(TxAltura.getText().isEmpty() || TxPeso.getText().isEmpty() || TxIdade.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Preencha os campos vazios!");
                return;
            }
            
        float altura = Float.parseFloat(TxAltura.getText());
        float peso = Float.parseFloat(TxPeso.getText());
        int idade = Integer.parseInt(TxIdade.getText());
        float calBasal, calTotal;
        
            if(buttonGroup1.getSelection().equals("Homen")){
                calBasal = 66 + (13.8f*peso) + (5*altura) - (6.8f*idade);
            }else{
                calBasal = 665 + (9.6f*peso) + (1.9f*altura) - (4.7f*idade);
            }
            
            if(CbAtv.getSelectedIndex() == 1){
                calTotal = calBasal*1.2f;
            }else if(CbAtv.getSelectedIndex() == 2){
                calTotal = calBasal*1.375f;
            }else if(CbAtv.getSelectedIndex() == 3){
                calTotal = calBasal*1.55f;
            }else if(CbAtv.getSelectedIndex() == 4){
                calTotal = calBasal*1.725f;
            }else {
                calTotal =calBasal*1.9f;
            }
          LbRespGB.setText(String.format("%.2f",calBasal));
          LbRespGT.setText(String.format("%.2f",calTotal));
        }
        catch(NumberFormatException exc){
            JOptionPane.showMessageDialog(null, "Números inválidos, preenchar corretamente os campos!");
        }
    }//GEN-LAST:event_BtCalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GastoCalorico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GastoCalorico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GastoCalorico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GastoCalorico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GastoCalorico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtCalcular;
    private javax.swing.JComboBox<String> CbAtv;
    private javax.swing.JPanel InputPanel;
    private javax.swing.JPanel JpGastoCalorico;
    private javax.swing.JLabel LbAltura;
    private javax.swing.JLabel LbAtv;
    private javax.swing.JLabel LbGB;
    private javax.swing.JLabel LbGT;
    private javax.swing.JLabel LbIdade;
    private javax.swing.JLabel LbPeso;
    private javax.swing.JLabel LbRespGB;
    private javax.swing.JLabel LbRespGT;
    private javax.swing.JLabel LbTitle;
    private javax.swing.JPanel OutPanel;
    private javax.swing.JTextField TxAltura;
    private javax.swing.JTextField TxIdade;
    private javax.swing.JTextField TxPeso;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    // End of variables declaration//GEN-END:variables
}
