/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package nutrisoft;

import javax.swing.JOptionPane;

/**
 *
 * @author breno
 */
public class Imc extends javax.swing.JFrame {

    /**
     * Creates new form Imc
     */
    public Imc() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JpImc = new javax.swing.JPanel();
        LbTitle = new javax.swing.JLabel();
        InputPanel = new javax.swing.JPanel();
        LbAltura = new javax.swing.JLabel();
        LbPeso = new javax.swing.JLabel();
        TxAltura = new javax.swing.JTextField();
        TxPeso = new javax.swing.JTextField();
        BtCalcular = new javax.swing.JButton();
        OutPanel = new javax.swing.JPanel();
        Lb1 = new javax.swing.JLabel();
        Lb2 = new javax.swing.JLabel();
        LbResp = new javax.swing.JLabel();
        LbInterp = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        JpImc.setBackground(new java.awt.Color(204, 204, 204));

        LbTitle.setBackground(new java.awt.Color(0, 0, 0));
        LbTitle.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        LbTitle.setForeground(new java.awt.Color(0, 0, 0));
        LbTitle.setText("Cálculo de IMC");

        InputPanel.setBackground(new java.awt.Color(204, 204, 204));
        InputPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        LbAltura.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LbAltura.setForeground(new java.awt.Color(0, 0, 0));
        LbAltura.setText("Altura (m):");

        LbPeso.setBackground(new java.awt.Color(0, 0, 0));
        LbPeso.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LbPeso.setForeground(new java.awt.Color(0, 0, 0));
        LbPeso.setText("Peso (Kg):");

        TxAltura.setBackground(new java.awt.Color(255, 255, 255));

        TxPeso.setBackground(new java.awt.Color(255, 255, 255));

        BtCalcular.setBackground(new java.awt.Color(255, 255, 255));
        BtCalcular.setForeground(new java.awt.Color(0, 0, 0));
        BtCalcular.setText("Calcular");
        BtCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtCalcularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout InputPanelLayout = new javax.swing.GroupLayout(InputPanel);
        InputPanel.setLayout(InputPanelLayout);
        InputPanelLayout.setHorizontalGroup(
            InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InputPanelLayout.createSequentialGroup()
                .addGroup(InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(InputPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtCalcular))
                    .addGroup(InputPanelLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LbAltura)
                            .addComponent(LbPeso))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                        .addGroup(InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TxAltura, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxPeso, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(16, 16, 16))
        );
        InputPanelLayout.setVerticalGroup(
            InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InputPanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbAltura)
                    .addComponent(TxAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbPeso)
                    .addComponent(TxPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtCalcular)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        OutPanel.setBackground(new java.awt.Color(204, 204, 204));
        OutPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Lb1.setBackground(new java.awt.Color(0, 0, 0));
        Lb1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Lb1.setForeground(new java.awt.Color(0, 0, 0));
        Lb1.setText("Resultado:");

        Lb2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Lb2.setForeground(new java.awt.Color(0, 0, 0));
        Lb2.setText("Interpetação:");

        LbResp.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N

        LbInterp.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N

        javax.swing.GroupLayout OutPanelLayout = new javax.swing.GroupLayout(OutPanel);
        OutPanel.setLayout(OutPanelLayout);
        OutPanelLayout.setHorizontalGroup(
            OutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OutPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(OutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Lb1)
                    .addComponent(Lb2))
                .addGap(66, 66, 66)
                .addGroup(OutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LbResp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LbInterp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        OutPanelLayout.setVerticalGroup(
            OutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OutPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(OutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LbResp, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lb1))
                .addGap(18, 18, 18)
                .addGroup(OutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Lb2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LbInterp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout JpImcLayout = new javax.swing.GroupLayout(JpImc);
        JpImc.setLayout(JpImcLayout);
        JpImcLayout.setHorizontalGroup(
            JpImcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpImcLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(JpImcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LbTitle)
                    .addComponent(InputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(OutPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        JpImcLayout.setVerticalGroup(
            JpImcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpImcLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(LbTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(InputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(OutPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JpImc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JpImc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtCalcularActionPerformed
       String mensagem;
      try{
       if(TxAltura.getText().isEmpty() || TxPeso.getText().isEmpty()){
           JOptionPane.showMessageDialog(null, "Preencha os campos vazios!");
           return;
       }
       float altura = Float.parseFloat(TxAltura.getText());
       float peso = Float.parseFloat(TxPeso.getText());
       
       float imc = peso/(altura/100 * altura/100);
       if(altura <= 0 || peso <= 0){
           JOptionPane.showMessageDialog(null, "Altura e peso devem ser maiores do que zero!");
           return;
       }
       if(imc < 18.9){
           mensagem = "Magreza";
       }else if(imc < 24.9){
           mensagem = "Normal";
       }else if(imc < 29.9){
           mensagem = "Sobrepeso";
       }else if(imc < 39.9){
           mensagem = "Obesidade";
       }else{
           mensagem = "Obesidade Grave";
       }
    
       LbResp.setText(String.format("%.2f", imc));
       LbInterp.setText(mensagem);
      }
      catch(NumberFormatException exc){
          JOptionPane.showMessageDialog(null,"Números inválidos, preencha corretamente!");
      }
      
      
    }//GEN-LAST:event_BtCalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Imc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Imc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Imc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Imc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Imc().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtCalcular;
    private javax.swing.JPanel InputPanel;
    private javax.swing.JPanel JpImc;
    private javax.swing.JLabel Lb1;
    private javax.swing.JLabel Lb2;
    private javax.swing.JLabel LbAltura;
    private javax.swing.JLabel LbInterp;
    private javax.swing.JLabel LbPeso;
    private javax.swing.JLabel LbResp;
    private javax.swing.JLabel LbTitle;
    private javax.swing.JPanel OutPanel;
    private javax.swing.JTextField TxAltura;
    private javax.swing.JTextField TxPeso;
    // End of variables declaration//GEN-END:variables
}
