/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package nutrisoft;

import javax.swing.JOptionPane;

/**
 *
 * @author breno
 */
public class Recomendacoes extends javax.swing.JFrame {

    /**
     * Creates new form Recomendacoes
     */
    public Recomendacoes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LbTitle = new javax.swing.JLabel();
        InputPanel = new javax.swing.JPanel();
        LbCD = new javax.swing.JLabel();
        TxCD = new javax.swing.JTextField();
        BtCalcular = new javax.swing.JButton();
        OutPanel = new javax.swing.JPanel();
        LbCarb = new javax.swing.JLabel();
        LbRespCarb = new javax.swing.JLabel();
        LbProt = new javax.swing.JLabel();
        LbRespProt = new javax.swing.JLabel();
        LbGord = new javax.swing.JLabel();
        LbRespGord = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        LbTitle.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        LbTitle.setForeground(new java.awt.Color(0, 0, 0));
        LbTitle.setText("Recomendações");

        InputPanel.setBackground(new java.awt.Color(204, 204, 204));
        InputPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        InputPanel.setForeground(new java.awt.Color(0, 0, 0));

        LbCD.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LbCD.setForeground(new java.awt.Color(0, 0, 0));
        LbCD.setText("Calorias diárias (kcal):");

        TxCD.setBackground(new java.awt.Color(255, 255, 255));
        TxCD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxCDActionPerformed(evt);
            }
        });

        BtCalcular.setBackground(new java.awt.Color(255, 255, 255));
        BtCalcular.setForeground(new java.awt.Color(0, 0, 0));
        BtCalcular.setText("Calcular");
        BtCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtCalcularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout InputPanelLayout = new javax.swing.GroupLayout(InputPanel);
        InputPanel.setLayout(InputPanelLayout);
        InputPanelLayout.setHorizontalGroup(
            InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(InputPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(BtCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(InputPanelLayout.createSequentialGroup()
                        .addComponent(LbCD)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TxCD)))
                .addContainerGap())
        );
        InputPanelLayout.setVerticalGroup(
            InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbCD)
                    .addComponent(TxCD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(BtCalcular, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                .addGap(23, 23, 23))
        );

        OutPanel.setBackground(new java.awt.Color(204, 204, 204));
        OutPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        LbCarb.setBackground(new java.awt.Color(0, 0, 0));
        LbCarb.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LbCarb.setForeground(new java.awt.Color(0, 0, 0));
        LbCarb.setText("Carboidratos (50%):");

        LbRespCarb.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LbRespCarb.setForeground(new java.awt.Color(0, 0, 0));

        LbProt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LbProt.setForeground(new java.awt.Color(0, 0, 0));
        LbProt.setText("Proteína (25%):");

        LbRespProt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LbRespProt.setForeground(new java.awt.Color(0, 0, 0));

        LbGord.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LbGord.setForeground(new java.awt.Color(0, 0, 0));
        LbGord.setText("Gordura (25%):");

        LbRespGord.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LbRespGord.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout OutPanelLayout = new javax.swing.GroupLayout(OutPanel);
        OutPanel.setLayout(OutPanelLayout);
        OutPanelLayout.setHorizontalGroup(
            OutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OutPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(OutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, OutPanelLayout.createSequentialGroup()
                        .addComponent(LbCarb)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                        .addComponent(LbRespCarb, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, OutPanelLayout.createSequentialGroup()
                        .addGroup(OutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LbProt)
                            .addComponent(LbGord))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(OutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(LbRespProt, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(LbRespGord, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        OutPanelLayout.setVerticalGroup(
            OutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OutPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(OutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LbCarb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LbRespCarb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(OutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(OutPanelLayout.createSequentialGroup()
                        .addComponent(LbRespProt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LbRespGord, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(OutPanelLayout.createSequentialGroup()
                        .addComponent(LbProt)
                        .addGap(18, 18, 18)
                        .addComponent(LbGord)))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LbTitle)
                    .addComponent(InputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(OutPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LbTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(InputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(OutPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxCDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxCDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxCDActionPerformed

    private void BtCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtCalcularActionPerformed
      try{
          if(TxCD.getText().isEmpty()){
              JOptionPane.showMessageDialog(null, "Preencha o campo vazio!");
              return;
          }
      float calDiaria = Float.parseFloat(TxCD.getText());
      
      if(calDiaria <= 0){
          JOptionPane.showMessageDialog(null, "Calorias por dia devem ser maior do que zero!");
          return;
      }
      
      float carboidrato = calDiaria * 0.5f / 4f;
      float proteina = calDiaria * 0.25f / 4f;
      float gordura = calDiaria * 0.25f / 9f;
      
      LbRespCarb.setText(String.format("%.2f", carboidrato));
      LbRespProt.setText(String.format("%.2f", proteina));
      LbRespGord.setText(String.format("%.2f", gordura));
      }
      catch(NumberFormatException exc){
          JOptionPane.showMessageDialog(null, "Número Inválido, preencha corretamente!");
      }
    }//GEN-LAST:event_BtCalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Recomendacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Recomendacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Recomendacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Recomendacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Recomendacoes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtCalcular;
    private javax.swing.JPanel InputPanel;
    private javax.swing.JLabel LbCD;
    private javax.swing.JLabel LbCarb;
    private javax.swing.JLabel LbGord;
    private javax.swing.JLabel LbProt;
    private javax.swing.JLabel LbRespCarb;
    private javax.swing.JLabel LbRespGord;
    private javax.swing.JLabel LbRespProt;
    private javax.swing.JLabel LbTitle;
    private javax.swing.JPanel OutPanel;
    private javax.swing.JTextField TxCD;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
