/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package nutrisoft;

/**
 *
 * @author breno
 */
public class TelaInicial extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicial
     */
    public TelaInicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JpNutriSoft = new javax.swing.JPanel();
        BtImc = new javax.swing.JButton();
        BtGastoC = new javax.swing.JButton();
        BtRecomen = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JpNutriSoft.setBackground(new java.awt.Color(204, 204, 204));

        BtImc.setBackground(new java.awt.Color(255, 255, 255));
        BtImc.setForeground(new java.awt.Color(0, 0, 0));
        BtImc.setText("IMC");
        BtImc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtImcActionPerformed(evt);
            }
        });

        BtGastoC.setBackground(new java.awt.Color(255, 255, 255));
        BtGastoC.setForeground(new java.awt.Color(0, 0, 0));
        BtGastoC.setText("Gasto Calórico");
        BtGastoC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtGastoCActionPerformed(evt);
            }
        });

        BtRecomen.setBackground(new java.awt.Color(255, 255, 255));
        BtRecomen.setForeground(new java.awt.Color(0, 0, 0));
        BtRecomen.setText("Recomendações");
        BtRecomen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtRecomenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JpNutriSoftLayout = new javax.swing.GroupLayout(JpNutriSoft);
        JpNutriSoft.setLayout(JpNutriSoftLayout);
        JpNutriSoftLayout.setHorizontalGroup(
            JpNutriSoftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpNutriSoftLayout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addGroup(JpNutriSoftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtRecomen)
                    .addComponent(BtGastoC, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtImc, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(147, Short.MAX_VALUE))
        );
        JpNutriSoftLayout.setVerticalGroup(
            JpNutriSoftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpNutriSoftLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(BtImc)
                .addGap(18, 18, 18)
                .addComponent(BtGastoC)
                .addGap(18, 18, 18)
                .addComponent(BtRecomen)
                .addContainerGap(117, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JpNutriSoft, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JpNutriSoft, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtImcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtImcActionPerformed
        Imc telaImc = new Imc();
        telaImc.setVisible(true);
    }//GEN-LAST:event_BtImcActionPerformed

    private void BtGastoCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtGastoCActionPerformed
        GastoCalorico telaGC = new GastoCalorico();
        telaGC.setVisible(true);
    }//GEN-LAST:event_BtGastoCActionPerformed

    private void BtRecomenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtRecomenActionPerformed
        Recomendacoes telaRecomen = new Recomendacoes();
        telaRecomen.setVisible(true);
 
    }//GEN-LAST:event_BtRecomenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtGastoC;
    private javax.swing.JButton BtImc;
    private javax.swing.JButton BtRecomen;
    private javax.swing.JPanel JpNutriSoft;
    // End of variables declaration//GEN-END:variables
}
